- name: download java
  package:
    name: "{{item}}"
    state: present
  loop:
     - epel-release
     - java 
     
- name: download tomcat
  unarchive:
        src: "{{tomcat_url}}"
        dest: /opt
        remote_src: yes       

- name: copy context.xml
  template:
       src: context.xml
       dest: "{{tomcat_dir}}/conf/context.xml"
       force: yes

- name: download war file
  get_url:
    url: https://devops-b3-cbz.s3.ap-south-1.amazonaws.com/student.war 
    dest: "{{tomcat_dir}}/webapps/"

- name: download jdbc mysql driver       
  get_url:
    url: https://devops-b3-cbz.s3.ap-south-1.amazonaws.com/mysql-connector.jar
    dest: "{{tomcat_dir}}/lib/"

- name: Set httpd_can_network_connect flag on and keep it persistent across reboots
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes    
    
- name: start tomcat
  shell: "{{tomcat_dir}}/bin/catalina.sh run"    