- name: condition playbook
  hosts: all
  tasks:
    - debug: 
        msg: My OS is {{ansible_distribution}}
    - debug: 
        msg: My Ubuntu server is Awesome
      when: ansible_distribution == "RedHat"
